// ── Pricing Plans ─────────────────────────────────────────────────────────────
export const plans = [
  {
    id: 'T0',
    tier: 'T0',
    name: 'Spark',
    subtitle: 'Startup Launch',
    tag: 'ENTRY LEVEL',
    pages: '1 page',
    price: 3999,
    originalPrice: null,
    delivery: '6 days',
    cta: 'Choose Spark',
    ctaStyle: 'outline',
    isBestValue: false,
    discountBadge: null,
    features: [
      'Landing page',
      'Mobile responsive',
      'WhatsApp CTA',
      'Contact form',
      'Basic SEO',
      'Custom color palette',
    ],
    complimentary: [
      'Free SSL',
      'WhatsApp support during project',
      'Basic SEO',
      '1 revision',
      '7-day bug fix',
    ],
  },
  {
    id: 'T1',
    tier: 'T1',
    name: 'Launchpad',
    subtitle: 'Starter',
    tag: 'STARTER',
    pages: '1–2 pages',
    price: 5999,
    originalPrice: null,
    delivery: '12 days',
    cta: 'Choose Launchpad',
    ctaStyle: 'outline',
    isBestValue: false,
    discountBadge: null,
    features: [
      'Everything in Spark',
      'React + motion animation',
      'Google Analytics setup',
      'Branded typography system',
    ],
    complimentary: [
      'Free SSL',
      'WhatsApp support',
      'Basic SEO',
      '1 revision',
      '7-day bug fix',
    ],
  },
  {
    id: 'T2',
    tier: 'T2',
    name: 'Velocity',
    subtitle: 'Growth',
    tag: 'GROWTH',
    pages: '3–5 pages',
    price: 9999,
    originalPrice: null,
    delivery: '16 days',
    cta: 'Choose Velocity',
    ctaStyle: 'outline',
    isBestValue: false,
    discountBadge: null,
    features: [
      'Everything in Launchpad',
      'Multipage (3+)',
      'Google Auth',
      'Maps & form integration',
      'Free server deployment',
    ],
    complimentary: [
      'Free SSL',
      'WhatsApp support',
      'Basic SEO',
      '1 revision',
      '7-day bug fix',
    ],
  },
  {
    id: 'T3',
    tier: 'T3',
    name: 'Empire',
    subtitle: 'Business',
    tag: 'BUSINESS',
    pages: '6–8 pages',
    price: 12999,
    originalPrice: 15999,
    delivery: '22 days',
    cta: 'Choose Empire',
    ctaStyle: 'neon',
    isBestValue: true,
    discountBadge: { label: '18% OFF', color: 'green' },
    features: [
      'Everything in Velocity',
      'Complete SEO setup',
      'Free domain (1 year)',
      'Speed optimization',
      'Multi-factor auth system',
      'Admin panel',
      '3 months maintenance',
    ],
    complimentary: [
      'Free SSL',
      'Free domain',
      'WhatsApp support',
      'Basic SEO',
      '1 revision',
      '30-day bug fix',
    ],
  },
  {
    id: 'T4',
    tier: 'T4',
    name: 'Nexus',
    subtitle: 'E-Commerce',
    tag: 'E-COMMERCE',
    pages: '9–12 pages',
    price: 19999,
    originalPrice: 24999,
    delivery: '30 days',
    cta: 'Choose Nexus',
    ctaStyle: 'blue',
    isBestValue: false,
    discountBadge: { label: '20% OFF', color: 'blue' },
    features: [
      'Everything in Empire',
      'Payment gateway',
      'Order tracking',
      'Automated emails',
      'E-commerce store',
      '6 months maintenance',
    ],
    complimentary: [
      'Free SSL',
      'Free domain',
      'WhatsApp support',
      'Basic SEO',
      '1 revision',
      '30-day bug fix',
    ],
  },
];

// ── Compare Table Data ─────────────────────────────────────────────────────────
export const compareRows = [
  { feature: 'Landing page',              t0: 'yes', t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Mobile responsive',         t0: 'yes', t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'WhatsApp CTA',              t0: 'yes', t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Contact form',              t0: 'yes', t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Basic SEO',                 t0: 'yes', t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Custom color palette',      t0: 'yes', t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'React + motion animation',  t0: 'no',  t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Google Analytics setup',    t0: 'no',  t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Branded typography system', t0: 'no',  t1: 'yes', t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Multipage (3+)',            t0: 'no',  t1: 'no',  t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Google Auth',               t0: 'no',  t1: 'no',  t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Maps & form integration',   t0: 'no',  t1: 'no',  t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Free server deployment',    t0: 'addon',t1:'addon',t2: 'yes', t3: 'yes', t4: 'yes' },
  { feature: 'Complete SEO setup',        t0: 'no',  t1: 'no',  t2: 'no',  t3: 'yes', t4: 'yes' },
  { feature: 'Free domain (1 year)',      t0: 'no',  t1: 'no',  t2: 'no',  t3: 'yes', t4: 'yes' },
  { feature: 'Speed optimization',        t0: 'no',  t1: 'no',  t2: 'no',  t3: 'yes', t4: 'yes' },
  { feature: 'Multi-factor auth system',  t0: 'no',  t1: 'no',  t2: 'no',  t3: 'yes', t4: 'yes' },
  { feature: 'Admin panel',               t0: 'no',  t1: 'no',  t2: 'no',  t3: 'yes', t4: 'yes' },
  { feature: '3 months maintenance',      t0: 'no',  t1: 'no',  t2: 'no',  t3: 'yes', t4: 'no'  },
  { feature: '6 months maintenance',      t0: 'no',  t1: 'no',  t2: 'no',  t3: 'no',  t4: 'yes' },
  { feature: 'Payment gateway',           t0: 'no',  t1: 'no',  t2: 'no',  t3: 'no',  t4: 'yes' },
  { feature: 'Order tracking',            t0: 'no',  t1: 'no',  t2: 'no',  t3: 'no',  t4: 'yes' },
  { feature: 'Automated emails',          t0: 'no',  t1: 'no',  t2: 'no',  t3: 'no',  t4: 'yes' },
  { feature: 'E-commerce store',          t0: 'no',  t1: 'no',  t2: 'no',  t3: 'no',  t4: 'yes' },
  { feature: 'Delivery time', isDelivery: true,
    t0: '6 days', t1: '12 days', t2: '16 days', t3: '22 days', t4: '30 days' },
];

// ── Add-ons ───────────────────────────────────────────────────────────────────
export const addons = [
  { id:'a1',  name:'Logo Design',             price:'₹1,499',        desc:'5 custom logos, 3 concepts, 2 revisions',                   icon:'Pen'         },
  { id:'a2',  name:'Brand Identity Kit',      price:'₹2,999',        desc:'Logo, color palette, fonts & brand guidelines',             icon:'Layers'      },
  { id:'a3',  name:'Content Writing',         price:'₹799/page',     desc:'Professional copy written for each page',                   icon:'FileText'    },
  { id:'a4',  name:'Advanced SEO',            price:'₹1,999',        desc:'Keyword research, meta tags, sitemaps, Google Search Console',icon:'Search'    },
  { id:'a5',  name:'Social Media Integration',price:'₹499',          desc:'Social feeds embedded on the site',                         icon:'Share2'      },
  { id:'a6',  name:'Social Media Ad Campaign',price:'₹2,499',        desc:'1-month campaign setup (Meta + Google Ads)',                 icon:'Megaphone'   },
  { id:'a7',  name:'CMS Setup',               price:'₹2,999',        desc:'Self-edit dashboard so clients update content themselves',   icon:'LayoutDashboard'},
  { id:'a8',  name:'WhatsApp Business Setup', price:'₹999',          desc:'Auto-replies, catalog & business profile setup',            icon:'MessageCircle'},
  { id:'a9',  name:'Website Redesign',        price:'₹2,999',        desc:'Full visual redesign of an existing site',                   icon:'RefreshCw'   },
  { id:'a10', name:'Domain Setup',            price:'₹499',          desc:'We connect your domain to your code',                       icon:'Globe'       },
  { id:'a11', name:'ChatBot Integration',     price:'₹3,499',        desc:'Bot on website or WhatsApp',                                icon:'Bot'         },
  { id:'a12', name:'Multilingual Support',    price:'₹999/language', desc:'Add multiple language support',                             icon:'Languages'   },
  { id:'a13', name:'Maintenance Extension',   price:'₹999/month',    desc:'Ongoing monthly updates & support',                         icon:'Wrench'      },
];

// ── Additional Services ───────────────────────────────────────────────────────
export const services = [
  { id:'s1', name:'Mobile App (React Native)', price:'₹24,999', desc:'Android + iOS app for existing website' },
  { id:'s2', name:'Custom Admin Dashboard',    price:'₹6,499',  desc:'Tailored admin panel built for your workflow' },
  { id:'s3', name:'API Integration',           price:'₹4,999',  desc:'Connect 3rd party APIs to your site' },
  { id:'s4', name:'Database Setup',            price:'₹4,999',  desc:'Structured database architecture & setup' },
  { id:'s5', name:'UI/UX Design Only',         price:'₹4,999',  desc:'Figma design without development' },
  { id:'s6', name:'Website Rebuild',           price:'₹4,999',  desc:'Complete rebuild from scratch' },
  { id:'s7', name:'PWA Conversion',            price:'₹999',    desc:'Turn existing site into an installable app' },
];

// ── Complimentary Items ───────────────────────────────────────────────────────
export const complimentaryItems = [
  { id:'c1', label:'Free SSL Certificate',         detail:'All tiers',  icon:'ShieldCheck' },
  { id:'c2', label:'Mobile Responsive',            detail:'All tiers',  icon:'Smartphone'  },
  { id:'c3', label:'WhatsApp Support',             detail:'During project — all tiers', icon:'MessageCircle' },
  { id:'c4', label:'Basic SEO',                    detail:'All tiers',  icon:'BarChart2'   },
  { id:'c5', label:'1 Round of Revision',          detail:'All tiers',  icon:'RefreshCw'   },
  { id:'c6', label:'7-Day Post-Launch Bug Fix',    detail:'T0 – T2',    icon:'Bug'         },
  { id:'c7', label:'30-Day Post-Launch Bug Fix',   detail:'T3 & T4',    icon:'Bug'         },
  { id:'c8', label:'Free Domain (1 year)',         detail:'T3 & T4',    icon:'Globe'       },
];
